### ISSUE TITLE
Unable to use

### ISSUE THREAD

**Issue by linonetwo** [phBalance/colour-contrast#3]
ERROR in ./node_modules/@phbalance/contrast-colour/colour.es6.js
  Module not found: Error: Can't resolve 'color' in '/Users/xxx/node_modules/@phbalance/contrast-colour'
   @ ./node_modules/@phbalance/contrast-colour/colour.es6.js 2:0-21 2:109-110 2:125-126 2:137-138
   @ ./src/gui/renderer/app/proxy-list/getContentTypeHint.tsx
   @ ./src/gui/renderer/app/proxy-list/index.tsx
   @ ./src/gui/router.ts
   @ ./src/gui/renderer/main.tsx
   @ multi ./.build/gui/dev-client ./src/gui/renderer/main.tsx

**Comment by linonetwo** [comment]
You are using import, which is causing error.

**Comment by phBalance** [comment]
Hi @linonetwo,
  the color package is setup as a peer dependency rather than a dependency which would be included directly. I see that my documentation didn't mention this in the install phase and I'll fix that.

   In the meantime, just to be sure, did you "npm install --save color"?

**Comment by linonetwo** [comment]
No, I didn't know that, maybe make it clear in the doc...
